# Generated by Django 4.0.3 on 2022-04-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rental name')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Check-in date')),
                ('checkout', models.DateField(verbose_name='Check-out date')),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rent_app.rental')),
            ],
        ),
    ]
