# Generated by Django 4.0.3 on 2022-04-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['checkin', 'checkout']},
        ),
    ]
